global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'authentication-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['authentication-service:7000']

  - job_name: 'common-data-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['common-data-service:9000']

  - job_name: 'search-suggestion-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['search-suggestion-service:7100']

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-service:7200']

  - job_name: 'react-ui'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['react-ui:3000']
      
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.11.142:9100']
      #thay bang ip cua node can giam sat
  - job_name: 'cadvisor'
    static_configs:    
      - targets: ['192.168.11.142:8081']
      #thay bang ip cua node can giam sat 