# DaemonSet for cAdvisor
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cadvisor
  namespace: default
spec:
  selector:
    matchLabels:
      app: cadvisor
  template:
    metadata:
      labels:
        app: cadvisor
    spec:
      containers:
      - name: cadvisor
        image: google/cadvisor:latest
        ports:
          - containerPort: 8080  # Default port for cAdvisor
            hostPort: 8081       # Optional: makes cAdvisor available on each node's IP at port 8081
            name: cadvisor-port
        volumeMounts:
          - name: docker-sock
            mountPath: /var/run/docker.sock
          - name: sys
            mountPath: /sys
            readOnly: true
          - name: docker-lib
            mountPath: /var/lib/docker
            readOnly: true
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: sys
          hostPath:
            path: /sys
        - name: docker-lib
          hostPath:
            path: /var/lib/docker
---
# Optional Service to expose cAdvisor metrics
apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: cadvisor
  ports:
    - protocol: TCP
      port: 8081       # The port exposed within the cluster
      targetPort: 8080 # The port cAdvisor is listening on inside the container
  type: ClusterIP     # Use LoadBalancer if you need external access
