apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-db
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - image: dexlo/mysql
        name: mysql-db-con
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: ecommerce-app-config
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: ecommerce_app_database
        - name: MYSQL_USER
          value: mysqluser
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: ecommerce-app-config
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 3306
          name: mysql-port
        # volumeMounts:
        # - mountPath: ./mysql-db/user.sql:/docker-entrypoint-initdb.d/user.sql
        #   name: mysql-db
        volumeMounts:
          - mountPath: /docker-entrypoint-initdb.d/user.sql
            name: mysql-db
            subPath: user.sql
      # volumes:
      # - name: mysql-db
      #   emptyDir: {}
      volumes:
        - name: mysql-db
          hostPath:
            path: /home/g21521926/mysql-db/user.sql  # Đảm bảo đường dẫn này đúng trên hệ thống của bạn
            type: File

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-db
  name: mysql-db
spec:
  type: ClusterIP
  ports:
  - name: "mysql-svc"
    port: 3306
    targetPort: 3306
  selector:
    app: mysql-db
  
