# DaemonSet for Node Exporter
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: default
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostNetwork: true     # Allows Node Exporter to use the host network
      hostPID: true         # Enables Node Exporter to see the host's process IDs
      containers:
      - name: node-exporter
        image: quay.io/prometheus/node-exporter:latest
        args:
          - "--path.rootfs=/host"
        ports:
          - containerPort: 9100  # Default port for Node Exporter
            hostPort: 9100       # Expose the port on the host
            name: metrics
        volumeMounts:
          - name: host-root
            mountPath: /host
            readOnly: true
      volumes:
        - name: host-root
          hostPath:
            path: /
            type: Directory
