apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment-service
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - image: dexlo/payment:mo
        name: payment-service-container

        env:
        - name: DB_PASS
          valueFrom:
                configMapKeyRef:
                name: ecommerce-app-config
                key: DB_PASS
        - name: DB_HOST
          value: mysql-db
        - name: DB_PORT
          value: 3306
        - name: DB_USER
          value: mysqluser
        - name: DB_SCHEMA
          value: ecommerce_app_database
        - name: ACTIVE_PROFILE
          value: dev
        - name: PORT
          value: 9050 
                 
        ports:
        - containerPort: 9050
          name: payment-service-port-deploy

      volumes:
      - name: payment-service
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: payment-service
  name: payment-service
spec:
  type: LoadBalancer
  ports:
  - name: "payment-service-svc"
    port: 9050
    targetPort: 9050
  selector:
    app: payment-service
  
