# ConfigMap for Prometheus Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'authentication-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['authentication-service:7000']

      - job_name: 'common-data-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['common-data-service:9000']

      - job_name: 'search-suggestion-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['search-suggestion-service:7100']

      - job_name: 'payment-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['payment-service:7200']

      - job_name: 'react-ui'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['react-ui:3000']
          
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['192.168.11.142:9100']
          #thay bang ip cua node can giam sat
      - job_name: 'cadvisor'
        static_configs:    
          - targets: ['192.168.11.142:8081']
          #thay bang ip cua node can giam sat 

---
# Deployment for Prometheus
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
          - containerPort: 9090
            name: prometheus-port
        volumeMounts:
          - name: prometheus-config-volume
            mountPath: /etc/prometheus
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config

---
# Service for Prometheus
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: default
spec:
  type: LoadBalancer  # Expose externally; use ClusterIP if internal-only
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090        # External port
      targetPort: 9090  # Container port where Prometheus listens
