apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ui-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-ui
  template:
    metadata:
      labels:
        app: react-ui
    spec:
      containers:
        - name: react-ui
          image: dexlo/ui:mo
          ports:
            - containerPort: 3000
              name: react-ui-port
          env:
            - name: REACT_APP_STRIPE_PUBLISH_KEY
              value: pk_test_51H805Oa3n3j3JVXUotWOsdf223PXI2ZehJ0s4QSQK0WjEJer78w87wer8h2u3bo32sTVcxyh5bDuulBildNrp
            - name: REACT_APP_COMMON_DATA_SERVICE_PORT
              value: "9000"
            - name: REACT_APP_ENVIRONMENT
              value: dev
          volumeMounts:
            - name: client
              mountPath: /usr/src/app
            - name: node-modules
              mountPath: /usr/src/app/node_modules
      volumes:
        - name: client
          emptyDir: {}
        - name: node-modules
          emptyDir: {}  
---
apiVersion: v1
kind: Service
metadata:
  name: react-ui-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: react-ui
  ports:
    - protocol: TCP
      port: 3000           # Exposes port 3000 on the load balancer
      targetPort: 3000     # Routes to port 3000 in the container
